#!/bin/bash

set -e

PROD_DIR=/groups/shrineflow/y24-pipeline
LOCAL_DIR=$(git rev-parse --show-toplevel)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
#cp "${PROD_DIR}/pipe/accomplice/sg_config.py" "${LOCAL_DIR}/pipe/accomplice/sg_config.py"

# make shelves read-only if this is prod
if [ "prod" = "${BRANCH}" ]; then
    chmod -R -w pipeline/software/maya/shelves/
else
    chmod -R +w pipeline/software/maya/shelves/
fi
